name: Publish Package to npmjs

on:
  release:
    types: [released, prereleased]

permissions:  
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TAG: ${{ github.event.action == 'prereleased' && 'alpha' || 'latest' }}
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build
      - run: npm publish --access public --tag $NPM_TAG
